### PR TITLE
Update weekly from issues

### PR DESCRIPTION
**Pull request by codeworm96**
Work in progress: Currently these are only raw output of the generator.
@arrowrowe @gaocegege

### CODE REVIEW

**Comment by at15** [comment]
btw: what about comments not in yaml (mostly from me /w\)

**Comment by gaocegege** [comment]
It seems that the link doesn't work: https://github.com/codeworm96/weekly/blob/ea13953e3b62815f82aafbabcc3313efd4a659ce/2016/2016-11-09-weekly.md

**Comment by codeworm96** [comment]
@gaocegege fixed.

BTW: The generator uses HashMap which doesn't guarantee order, so the order of posts may change if you run it again. Do we need to fix it?

@at15 It seems we can only(?) handle them manually... /w\

**Comment by gaocegege** [comment]
There is no need to do it, IMO. Well done.

**Comment by codeworm96** [comment]
Unstructured posts have been added manually.

~~关爱周报生成器，从我做起，拒绝不规范投稿。~~

**Comment by gaocegege** [comment]
@at15 You should take a look at https://github.com/dyweb/weekly/pull/19#issuecomment-309040651

**Comment by at15** [comment]
..../w\

**Comment by at15** [comment]
so merge it? cc @ComMouse @gaocegege ?

LGTM

**Comment by gaocegege** [comment]
Should we merge? @codeworm96 @at15 @arrowrowe

**Comment by arrowrowe** [comment]
LGTM

**Comment by gaocegege** [comment]
Wait @ComMouse 's response.

**Comment by ComMouse** [comment]
LGTM

**Comment by swaylq** [comment]
Awesome !

**Pull request merged**
