### PR TITLE
weekly: Add

### LINKED ISSUE #21: Weekly/72 for 2018/4/23
... 我只是说说而已 /w\

### PR DESCRIPTION
**Pull request by gaocegege**
Proudly generated with [dy-weekly-generator](https://github.com/codeworm96/dy-weekly-generator)

Close #21 

Signed-off-by: Ce Gao <gaoce@caicloud.io>

### CODE REVIEW

**Comment by ComMouse** [comment]
LGTM

BTW `@` seems with no link?

**Comment by gaocegege** [comment]
Yeah, it is to be implemented from generator side.

**Comment by gaocegege** [comment]
There are some new changes here:

- Update the HTML page
- Update the gemfile lock.

PTAL

**Pull request merged**
